---
settings:
  name: SaaS Backup For Partner Central
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-tw,us-en,ja-jp,ko-kr,zh-cn,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: Partner Central
    entries:
    - title: NetApp SaaS備份合作夥伴中心文件
      url: "/index.html"
    - title: 版本資訊
      entries:
      - title: 新功能與更新
        url: "/partnercentral_reference_new.html"
      - title: 已知問題與限制
        url: "/partnercentral_reference_limitations.html"
    - title: 註冊Partner Central
      url: "/partnercentral_task_register.html"
    - title: 新增及管理客戶
      url: "/partnercentral_task_add_and_manage_customers.html"
    - title: 監控客戶工作
      url: "/partnercentral_task_monitor.html"
    - title: 產生報告
      url: "/partnercentral_task_generate_reports.html"
    - title: 管理設定
      entries:
      - title: 管理通知
        url: "/partnercentral_task_manage_notifications.html"
      - title: 管理角色
        url: "/partnercentral_task_manage_roles.html"
      - title: 管理金鑰
        url: "/partnercentral_task_manage_keys.html"
    - title: 統計資料
      url: "/partnercentral_reference_statistics.html"
    - title: 何處可取得協助及尋找資訊
      url: "/partnercentral_reference_get_help_find_info.html"
